// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://your-project.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2cnl5eHVrZ2xzZXV5emNtbHB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNDIxNzIsImV4cCI6MjA1NTYxODE3Mn0.KpDwR9iSG9-NYYMpFtk1MI2nYxLoCDRid0imTRYt5KQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);